spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    # 数据源
    hikari:
      username: root
      password: CgY1997%!@
      # mysql-connector-java >= 6.x com.mysql.cj.jdbc.Driver
      # mysql-connector-java <= 5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ

  #        service: 优先读取这里的服务名 而不是 spring.application.name
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: my-content-center

server:
  port: 8010

#my-user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    enabled: true
    clients: my-user-center

logging:
  level:
    com.itmuch.mycontentcenter.feignclient.UserCenterFeignClient: debug

feign:
  client:
    config:
      # 想要调用的微服务的名称
      my-user-center:
        loggerLevel: full
