spring:
  datasource:
    url: jdbc:mysql://localhost:3306/content_center
    # 数据源
    hikari:
      username: root
      password: CgY1997%!@
      # mysql-connector-java >= 6.x com.mysql.cj.jdbc.Driver
      # mysql-connector-java <= 5.x com.mysql.jdbc.Driver
      driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        cluster-name: BJ
    sentinel:
      filter:
        # 打开/关闭掉对Spring MVC端点的保护
        enabled: true
      transport:
        # 指定sentinel 控制台的地址
        dashboard: localhost:8080
      web-context-unify: false
    stream:
      rocketmq:
        binder:
          name-server: 127.0.0.1:9876
        bindings:
          output:
            producer:
              transactional: true
              group: tx-add-bonus-group
      bindings:
        output:
          # 用来指定topic
          destination: add-bonus

  #        service: 优先读取这里的服务名 而不是 spring.application.name
  application:
    # 服务名称尽量用-，不要用_，不要用特殊字符
    name: my-content-center

  main:
    allow-bean-definition-overriding: true

server:
  port: 8010

#my-user-center:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
ribbon:
  eager-load:
    enabled: true
    clients: my-user-center

logging:
  level:
    com.itmuch.mycontentcenter.feignclient.UserCenterFeignClient: debug

feign:
  client:
    config:
      # 想要调用的微服务的名称
      default:
        loggerLevel: full
        requestInterceptors:
          - com.itmuch.mycontentcenter.feignclient.interceptor.TokenRelayRequestInterceptor

  httpclient:
    # 让feign使用apache httpclient做请求;而不是默认的urlConnection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
  sentinel:
    # 为feign整合sentinel
    enabled: true
#  okhttp:
#    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
resttemplate:
  sentinel:
  # 关闭@SentinelRestTemplate注解
  enabled: true


jwt:
  secret: aaaaabbbbbccccccdddddaaaaabbbbbccccccdddddaaaaabbbbbccccccddddd
  # 有效期，单位秒，默认2周
  expire-time-in-second: 1209600
